import pygame

# Настройки экрана
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "Котик и мышки"

# Настройки отображения
SHOW_HITBOXES = False
HITBOX_COLOR = (255, 0, 0, 150)
FPS = 60

# Параметры игрока
PLAYER_WIDTH = 200
PLAYER_HEIGHT = 140
PLAYER_SPEED = 5
PLAYER_JUMP_POWER = 15
PLAYER_GRAVITY = 0.8
PLAYER_HITBOX_WIDTH = 70
PLAYER_HITBOX_HEIGHT = 70
PLAYER_HITBOX_OFFSET_X = 45
PLAYER_HITBOX_OFFSET_Y = 60

# Параметры платформ
PLATFORM_HEIGHT = 70
PLATFORM_HITBOX_HEIGHT = 20
PLATFORM_HITBOX_OFFSET = 17
PLATFORM_WIDTH = 200
MIN_PLATFORM_WIDTH = 150
MAX_PLATFORM_WIDTH = 300
PLATFORM_SPACING_MIN = 150
PLATFORM_SPACING_MAX = 300

# Генерация мира
WORLD_OFFSET_MARGIN = 100
VISIBLE_PLATFORM_RANGE = 100
INITIAL_PLATFORMS = 5

# Цвета
DEBUG_TEXT_COLOR = (255, 255, 255)

# Пути к файлам
ASSETS_DIR = "assets"
BACKGROUND_IMAGE = "background.png"
PLATFORM_IMAGE = "grass.png"
PLAYER_IMAGE = "cat.png"

# Клавиши управления
MOVE_LEFT_KEY = pygame.K_LEFT
MOVE_RIGHT_KEY = pygame.K_RIGHT
JUMP_KEY = pygame.K_SPACE
TOGGLE_HITBOX_KEY = pygame.K_h
